# Deploy static website to `gh-pages` branch
name: pages-build

# Triggers for the workflow to run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs to run on trigger
jobs:
  # Validate
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Environment
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      # Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate icons & validate icons
      - name: Validate all icons and metadata
        run: python scripts/generate.py

      # Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: icons.raivo-otp.com
          exclude_assets: '.gitignore'
          enable_jekyll: false
          keep_files: true
